# Generated by Django 4.2.2 on 2023-07-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="verification_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
