# Generated by Django 4.2.2 on 2023-06-18 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmedia",
            name="user",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="city",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="group",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="manager",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="state",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="works_where",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="email address"
            ),
        ),
        migrations.DeleteModel(
            name="CustomGroup",
        ),
        migrations.DeleteModel(
            name="SocialMedia",
        ),
    ]
