# Generated by Django 4.2.2 on 2023-07-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_alter_customuser_verification_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="verification_code",
            new_name="email_verification_code",
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_verification_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
