# Generated by Django 4.2.2 on 2023-07-01 00:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_customuser_verified_alter_customuser_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(help_text="...", max_length=254, null=True),
        ),
    ]
