# Generated by Django 4.2.2 on 2023-07-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0003_rename_verification_code_customuser_email_verification_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone_verified",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
