# Generated by Django 4.2.2 on 2023-07-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_alter_customuser_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="verified",
            field=models.BooleanField(
                default=False, help_text="Complete User Verification", null=True
            ),
        ),
    ]
