# Generated by Django 4.2.2 on 2023-07-01 21:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_customuser_email_verified_customuser_phone_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="verified",
        ),
    ]
