# Generated by Django 4.2.2 on 2023-07-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_customuser_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enter_email_verification_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='enter_phone_verification_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
