# Generated by Django 4.2.2 on 2023-07-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_customuser_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuserverification",
            name="email_code_entered",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="customuserverification",
            name="email_code_matched",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="customuserverification",
            name="email_code_sent",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name="customuserverification",
            name="verification_datetime",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
